---
- name: One Node Elasticsearch
  hosts: search
  become: True
  roles:
    - { role: ansiblebit.oracle-java, oracle_java_set_as_default: yes }
    - { role: elasticsearch, es_instance_name: "node1" , es_data_dirs: "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", es_work_dir: "/opt/elasticsearch/temp", 
        es_config: {
            node.name: "node1", 
            discovery.zen.ping.unicast.hosts: "localhost:9301",
            http.port: 9201,
            transport.tcp.port: 9301,
            node.data: true,
            node.master: true,
            bootstrap.mlockall: true,
            discovery.zen.ping.multicast.enabled: false } 
        }
  vars:
